# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Starbucks CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

  install_dependencies:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
  tests:
    runs-on: self-hosted
    needs: install_dependencies
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Run Tests 
      run: npm run test
  start_application:
    runs-on: self-hosted
    needs: tests
    # defaults:
    #     run:
    #       working-directory: ./starbucks
    steps:
      - name: Start Application
        run: echo "Application Started"
