# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Starbucks CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  checkout:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

  install_dependencies:
    runs-on: self-hosted
    needs: checkout
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
  lint:
    runs-on: self-hosted
    needs: install_dependencies
    steps:
    - name: linting the code
      run: echo "linting completed"
  tests:
    runs-on: self-hosted
    needs: install_dependencies
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Run Tests 
      run: npm run test
  # start_application:
  #   runs-on: self-hosted
  #   needs: tests
  #   # defaults:
  #   #     run:
  #   #       working-directory: ./starbucks
  #   steps:
  #     - name: Start Application
  #       run: echo "Application Started"
  sonarqube:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate SCM analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2 # Use the latest version from GitHub Marketplace
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=STARBUCKS_CLONE_PROJECT
            -Dsonar.sources=.

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  trivy_fs_scan:
    runs-on: self-hosted
    needs: tests
    steps:
      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          #exit-code: '1'
          severity: CRITICAL,HIGH
          ignore-unfixed: true
  docker_installation:
    runs-on: self-hosted
    needs: [ tests, sonarqube ]
    steps:
      - name: Build Docker Image
        run: |
          docker build -t starbucks-clone-image .
      - name: Verify Docker Image
        run: docker images | grep starbucks-clone-image      
  docker_image_scan:
    runs-on: self-hosted
    needs: docker_installation
    steps:
      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: starbucks-clone-image
          format: table
          # exit-code: '1'
          severity: CRITICAL,HIGH
          ignore-unfixed: true        
  run_docker_container:
    runs-on: self-hosted
    needs: docker_installation
    steps:
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name starbucks-clone-container starbucks-clone-image
      - name: Verify Docker Container is Running
        run: docker ps | grep starbucks-clone-container