# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Starbucks CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  checkout:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

  install_dependencies:
    runs-on: self-hosted
    needs: checkout
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
  tests:
    runs-on: self-hosted
    needs: install_dependencies
    # defaults:
    #   run:
    #     working-directory: ./starbucks
    steps:
    - name: Run Tests 
      run: npm run test
  start_application:
    runs-on: self-hosted
    needs: tests
    # defaults:
    #     run:
    #       working-directory: ./starbucks
    steps:
      - name: Start Application
        run: echo "Application Started"
  docker_installation:
    runs-on: self-hosted
    steps:
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
      - name: Verify Docker Installation
        run: docker --version
  image_build:
    runs-on: self-hosted
    needs: docker_installation
    steps:
      - name: Build Docker Image
        run: |
          docker build -t starbucks-clone-image .
      - name: Verify Docker Image
        run: docker images | grep starbucks-clone-image      
  run_docker_container:
    runs-on: self-hosted
    needs: image_build
    steps:
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --name starbucks-clone-container starbucks-clone-image
      - name: Verify Docker Container is Running
        run: docker ps | grep starbucks-clone-container